INSERT INTO games (title, steam_id) VALUES ("Wallpaper Engine", 431960);
INSERT INTO games (title, steam_id) VALUES ("H1Z1", 433850);
INSERT INTO games (title, steam_id) VALUES ("IKEA VR Experience", 447270);
INSERT INTO games (title, steam_id) VALUES ("Brine", 447940);
INSERT INTO games (title, steam_id) VALUES ("Judgment: Apocalypse Survival Simulation", 455980);
INSERT INTO games (title, steam_id) VALUES ("Fury Unleashed (The Badass Hero)", 465200);
INSERT INTO games (title, steam_id) VALUES ("Beholder", 475550);
INSERT INTO games (title, steam_id) VALUES ("Totally Accurate Battle Simulator", 508440);
INSERT INTO games (title, steam_id) VALUES ("Streets of Rogue", 512900);
INSERT INTO games (title, steam_id) VALUES ("Doorways: Old Prototype", 525780);
INSERT INTO games (title, steam_id) VALUES ("Resident Evil 7 / Biohazard 7 Teaser: Beginning Hour", 530620);
INSERT INTO games (title, steam_id) VALUES ("Lost Grimoires: Stolen Kingdom", 536780);
INSERT INTO games (title, steam_id) VALUES ("Puyo Puyo™Tetris® ", 546050);
INSERT INTO games (title, steam_id) VALUES ("GravNewton", 549100);
INSERT INTO games (title, steam_id) VALUES ("Underhero", 573320);
INSERT INTO games (title, steam_id) VALUES ("Yonder: The Cloud Catcher Chronicles", 580200);
INSERT INTO games (title, steam_id) VALUES ("Semispheres Soundtrack", 590350);
INSERT INTO games (title, steam_id) VALUES ("FINAL FANTASY XII THE ZODIAC AGE", 595520);
INSERT INTO games (title, steam_id) VALUES ("CHRONO TRIGGER", 613830);
INSERT INTO games (title, steam_id) VALUES ("Ravenfield", 636480);
INSERT INTO games (title, steam_id) VALUES ("In Game Adventure: Legend of Monsters", 640970);
INSERT INTO games (title, steam_id) VALUES ("Outpost Zero", 677480);
INSERT INTO games (title, steam_id) VALUES ("SPACE ASTEROID SHOOTER", 699460);
INSERT INTO games (title, steam_id) VALUES ("Beyond the Void", 700570);
INSERT INTO games (title, steam_id) VALUES ("Sakura Cupid", 733740);
INSERT INTO games (title, steam_id) VALUES ("Creatio Ex Nihilo: Aition", 738080);
INSERT INTO games (title, steam_id) VALUES ("Edna & Harvey: Harvey's New Eyes Developer Commentary", 752510);
INSERT INTO games (title, steam_id) VALUES ("PRO EVOLUTION SOCCER 2019", 770240);
INSERT INTO games (title, steam_id) VALUES ("Kitty Catsanova", 770770);
INSERT INTO games (title, steam_id) VALUES ("Wizard101", 799960);
INSERT INTO games (title, steam_id) VALUES ("Shining Resonance Refrain", 809890);
INSERT INTO games (title, steam_id) VALUES ("Assassin's Creed Odyssey", 812140);
INSERT INTO games (title, steam_id) VALUES ("CONCLUSE", 826230);
INSERT INTO games (title, steam_id) VALUES ("NEKO-NIN exHeart 2", 828580);
INSERT INTO games (title, steam_id) VALUES ("Alaskan Truck Simulator", 849100);
INSERT INTO games (title, steam_id) VALUES ("Space Elite Force", 855850);
INSERT INTO games (title, steam_id) VALUES ("GIRLS VR (CREATE + POSE in VR)", 879610);
INSERT INTO games (title, steam_id) VALUES ("TERRORHYTHM (TRRT) - OST", 889350);
INSERT INTO games (title, steam_id) VALUES ("Lucah: Born of a Dream", 896460);
INSERT INTO games (title, steam_id) VALUES ("Reigns: Game of Thrones", 897820);
INSERT INTO games (title, steam_id) VALUES ("Initial 2 : New Stage", 904310);
INSERT INTO games (title, steam_id) VALUES ("Welcome Above", 912660);
INSERT INTO games (title, steam_id) VALUES ("Catch The Kids", 915730);
INSERT INTO games (title, steam_id) VALUES ("Gimel Dimension", 916470);
INSERT INTO games (title, steam_id) VALUES ("Steel Division 2", 919640);
INSERT INTO games (title, steam_id) VALUES ("Love Letter", 926520);
INSERT INTO games (title, steam_id) VALUES ("BOLSOMITO", 930460);
INSERT INTO games (title, steam_id) VALUES ("Master of Typing", 936100);
INSERT INTO games (title, steam_id) VALUES ("Sea Dogs: City of Abandoned Ships", 937940);
INSERT INTO games (title, steam_id) VALUES ("Hentai Legends", 939180);
INSERT INTO games (title, steam_id) VALUES ("Our World Is Ended", 940650);
INSERT INTO games (title, steam_id) VALUES ("Stellaris - MegaCorp", 944290);
INSERT INTO games (title, steam_id) VALUES ("Fantasy Grounds - Odds and Ends, Volume 9 (Token Pack)", 946420);
INSERT INTO games (title, steam_id) VALUES ("Gangsta Sniper", 951640);
INSERT INTO games (title, steam_id) VALUES ("Fantasy Grounds - Savage Suzerain Adventure Deck (Savage Worlds)", 951790);
INSERT INTO games (title, steam_id) VALUES ("Zenkit", 952430);
INSERT INTO games (title, steam_id) VALUES ("Fantasy Grounds - Saints and Heroes, Volume 8 (Token Pack)", 957330);
INSERT INTO games (title, steam_id) VALUES ("Fantasy Grounds - B06: Cry of Ill Omen (5E)", 959460);
INSERT INTO games (title, steam_id) VALUES ("Steel Vampire Original Soundtrack", 959840);
INSERT INTO games (title, steam_id) VALUES ("Vile", 961420);
INSERT INTO games (title, steam_id) VALUES ("Warface - Free Anniversary Pack", 962430);
INSERT INTO games (title, steam_id) VALUES ("Fantasy Grounds - A07: Alchemist's Errand (Savage Worlds)", 962780);
INSERT INTO games (title, steam_id) VALUES ("Fantasy Grounds - The Haunting (CoC7E)", 963410);
INSERT INTO games (title, steam_id) VALUES ("VR Rome", 964460);
INSERT INTO games (title, steam_id) VALUES ("CarX Drift Racing Online - CarX Halloween", 965040);
INSERT INTO games (title, steam_id) VALUES ("Pathfinder: Kingmaker - Bloody Mess", 965950);
INSERT INTO games (title, steam_id) VALUES ("Fantasy Grounds - The Derelict (CoC7E)", 966750);
INSERT INTO games (title, steam_id) VALUES ("DOKA 2", 967250);
INSERT INTO games (title, steam_id) VALUES ("Bunny Mahjo", 968470);
INSERT INTO games (title, steam_id) VALUES ("Lovecraft's Untold Stories", 871420);
INSERT INTO games (title, steam_id) VALUES ("The Plague", 672040);
INSERT INTO games (title, steam_id) VALUES ("Shroud of the Avatar: Forsaken Virtues", 326160);
INSERT INTO games (title, steam_id) VALUES ("Dig or Die", 315460);
INSERT INTO games (title, steam_id) VALUES ("Coloring Pixels", 897330);
INSERT INTO games (title, steam_id) VALUES ("One Hour One Life", 595690);
INSERT INTO games (title, steam_id) VALUES ("Zero spring episode 1 English translation version", 951010);
INSERT INTO games (title, steam_id) VALUES ("Zero spring episode 1 Japanese version", 951070);
INSERT INTO games (title, steam_id) VALUES ("Super X Chess", 814990);
INSERT INTO games (title, steam_id) VALUES ("Arma 3", 107410);
INSERT INTO games (title, steam_id) VALUES ("Far Cry® 3", 220240);
INSERT INTO games (title, steam_id) VALUES ("Killing Floor 2", 232090);
INSERT INTO games (title, steam_id) VALUES ("Godus", 232810);
INSERT INTO games (title, steam_id) VALUES ("Robot Roller-Derby Disco Dodgeball", 270450);
INSERT INTO games (title, steam_id) VALUES ("Hotline Miami 2: Wrong Number", 274170);
INSERT INTO games (title, steam_id) VALUES ("FaceRig", 274920);
INSERT INTO games (title, steam_id) VALUES ("Rise of Nations: Extended Edition", 287450);
INSERT INTO games (title, steam_id) VALUES ("Sid Meier's Civilization VI", 289070);
INSERT INTO games (title, steam_id) VALUES ("RimWorld", 294100);
INSERT INTO games (title, steam_id) VALUES ("For Honor", 304390);
INSERT INTO games (title, steam_id) VALUES ("Enter the Gungeon", 311690);
INSERT INTO games (title, steam_id) VALUES ("Move or Die", 323850);
INSERT INTO games (title, steam_id) VALUES ("Phantom Breaker: Battle Grounds", 329490);
INSERT INTO games (title, steam_id) VALUES ("Joe's Diner", 346040);
INSERT INTO games (title, steam_id) VALUES ("Elite Dangerous", 359320);
INSERT INTO games (title, steam_id) VALUES ("Romance of the Three Kingdoms 13", 363150);
INSERT INTO games (title, steam_id) VALUES ("Tom Clancy's The Division", 365590);
INSERT INTO games (title, steam_id) VALUES ("Divinity: Original Sin Enhanced Edition", 373420);
INSERT INTO games (title, steam_id) VALUES ("DARK SOULS™ III", 374320);
INSERT INTO games (title, steam_id) VALUES ("Call of Duty: Modern Warfare 2", 10180);
INSERT INTO games (title, steam_id) VALUES ("Call of Duty: Modern Warfare 2 - Multiplayer", 10190);
INSERT INTO games (title, steam_id) VALUES ("Counter-Strike: Source", 240);
INSERT INTO games (title, steam_id) VALUES ("Left 4 Dead 2", 550);
INSERT INTO games (title, steam_id) VALUES ("Portal 2", 620);
INSERT INTO games (title, steam_id) VALUES ("Underworld Ascendant", 692840);
INSERT INTO games (title, steam_id) VALUES ("Gaia Beyond", 788630);
INSERT INTO games (title, steam_id) VALUES ("Bloody Trapland 2: Curiosity", 579840);
INSERT INTO games (title, steam_id) VALUES ("Worms W.M.D", 327030);
INSERT INTO games (title, steam_id) VALUES ("Pumpkin Death Garden", 951220);
INSERT INTO games (title, steam_id) VALUES ("Battle Royale: Survivors", 840130);
INSERT INTO games (title, steam_id) VALUES ("Base Defense", 632730);
INSERT INTO games (title, steam_id) VALUES ("Sigma Theory", 716640);
INSERT INTO games (title, steam_id) VALUES ("Plane Mechanic Simulator", 803980);
INSERT INTO games (title, steam_id) VALUES ("Nowhere Patrol", 961660);
INSERT INTO games (title, steam_id) VALUES ("HITMAN™", 236870);
INSERT INTO games (title, steam_id) VALUES ("Dungeons of Tal'Doria", 626130);
INSERT INTO games (title, steam_id) VALUES ("DJ Whip VR", 943970);
INSERT INTO games (title, steam_id) VALUES ("scram server", 896050);
INSERT INTO games (title, steam_id) VALUES ("Chronicon", 375480);
INSERT INTO games (title, steam_id) VALUES ("Spoorky Demo", 969550);
INSERT INTO games (title, steam_id) VALUES ("The Lost Legends of Redwall : The Scout", 656030);
INSERT INTO games (title, steam_id) VALUES ("MX vs ATV All Out", 520940);
INSERT INTO games (title, steam_id) VALUES ("Borderlands 2", 49520);
INSERT INTO games (title, steam_id) VALUES ("Crazy Machines VR", 802690);
INSERT INTO games (title, steam_id) VALUES ("Production Line", 591370);
INSERT INTO games (title, steam_id) VALUES ("Touhou Genso Wanderer -Reloaded-", 931500);
INSERT INTO games (title, steam_id) VALUES ("Tennis World Tour", 692030);
INSERT INTO games (title, steam_id) VALUES ("EVE Online", 8500);
INSERT INTO games (title, steam_id) VALUES ("Cube Universe", 820070);
INSERT INTO games (title, steam_id) VALUES ("Cube Universe Demo", 872120);
INSERT INTO games (title, steam_id) VALUES ("Mysterious Realms RPG", 752800);
INSERT INTO games (title, steam_id) VALUES ("AXE:SURVIVAL", 958230);
INSERT INTO games (title, steam_id) VALUES ("Tunnels of Despair", 635900);
INSERT INTO games (title, steam_id) VALUES ("Of Guards And Thieves", 302590);
INSERT INTO games (title, steam_id) VALUES ("Call of Duty: WWII - Multiplayer", 476620);
INSERT INTO games (title, steam_id) VALUES ("Call of Duty: WWII", 476600);
INSERT INTO games (title, steam_id) VALUES ("The Cursed Forest", 345430);
INSERT INTO games (title, steam_id) VALUES ("Heliborne", 433530);
INSERT INTO games (title, steam_id) VALUES ("One-way Ticket · 单程票", 856370);
INSERT INTO games (title, steam_id) VALUES ("Cuisine Royale", 884660);
INSERT INTO games (title, steam_id) VALUES ("Ascension", 320430);
INSERT INTO games (title, steam_id) VALUES ("The Guild 3", 311260);
INSERT INTO games (title, steam_id) VALUES ("TerraTech", 285920);
INSERT INTO games (title, steam_id) VALUES ("How About Spikes", 847570);
INSERT INTO games (title, steam_id) VALUES ("Boundless", 324510);
INSERT INTO games (title, steam_id) VALUES ("Fun Hospital", 829420);
INSERT INTO games (title, steam_id) VALUES ("Rise of Industry", 671440);
INSERT INTO games (title, steam_id) VALUES ("Citadel: Forged With Fire Server", 489650);
INSERT INTO games (title, steam_id) VALUES ("BLOCKPOST", 706990);
INSERT INTO games (title, steam_id) VALUES ("Citadel: Forged With Fire", 487120);
INSERT INTO games (title, steam_id) VALUES ("Mega Man 11 / Rock Man 11", 742300);
INSERT INTO games (title, steam_id) VALUES ("Ballistic Overkill", 296300);
INSERT INTO games (title, steam_id) VALUES ("Lucifer's Forest", 929000);
INSERT INTO games (title, steam_id) VALUES ("AS+CEND", 866430);
INSERT INTO games (title, steam_id) VALUES ("The Slater", 881690);
INSERT INTO games (title, steam_id) VALUES ("Post Scriptum - Beta Dedicated Server", 844650);
INSERT INTO games (title, steam_id) VALUES ("Battlerite Royale", 879160);
INSERT INTO games (title, steam_id) VALUES ("Nodge", 715590);
INSERT INTO games (title, steam_id) VALUES ("Consortium: The Tower", 626250);
INSERT INTO games (title, steam_id) VALUES ("MasterpieceVR", 504650);
INSERT INTO games (title, steam_id) VALUES ("GRIS", 683320);
INSERT INTO games (title, steam_id) VALUES ("Trüberbrook", 757300);
INSERT INTO games (title, steam_id) VALUES ("Pirates, Vikings, and Knights II Dedicated Server", 17575);
INSERT INTO games (title, steam_id) VALUES ("Total War: ROME II - Emperor Edition", 214950);
INSERT INTO games (title, steam_id) VALUES ("Total War Battles: KINGDOM", 300080);
INSERT INTO games (title, steam_id) VALUES ("Total War: ATTILA", 325610);
INSERT INTO games (title, steam_id) VALUES ("SHOGUN: Total War™ - Gold Edition", 345240);
INSERT INTO games (title, steam_id) VALUES ("MEDIEVAL: Total War™ - Gold Edition", 345260);
INSERT INTO games (title, steam_id) VALUES ("Total War: WARHAMMER", 364360);
INSERT INTO games (title, steam_id) VALUES ("Total War: WARHAMMER II", 594570);
INSERT INTO games (title, steam_id) VALUES ("Total War Saga: Thrones of Britannia", 712100);
INSERT INTO games (title, steam_id) VALUES ("Total War: THREE KINGDOMS", 779340);
INSERT INTO games (title, steam_id) VALUES ("STARDROP", 552880);
INSERT INTO games (title, steam_id) VALUES ("Mushroom Wars 2", 457730);
INSERT INTO games (title, steam_id) VALUES ("Dungeon Painter Studio", 592260);
INSERT INTO games (title, steam_id) VALUES ("BDSM: Big Drunk Satanic Massacre", 669950);
INSERT INTO games (title, steam_id) VALUES ("Pirates, Vikings, & Knights II", 17570);
INSERT INTO games (title, steam_id) VALUES ("Adventure Time: Pirates of the Enchiridion", 728240);
INSERT INTO games (title, steam_id) VALUES ("Party Hard 2 ", 572430);
INSERT INTO games (title, steam_id) VALUES ("A Flappy Bird in Real Life", 963830);
INSERT INTO games (title, steam_id) VALUES ("Transports", 659920);
INSERT INTO games (title, steam_id) VALUES ("NieR:Automata™", 524220);
INSERT INTO games (title, steam_id) VALUES ("A Piece of Wish upon the Stars", 899190);
INSERT INTO games (title, steam_id) VALUES ("Insurgence - Chains of Renegade", 912930);
INSERT INTO games (title, steam_id) VALUES ("Hot Dogs, Horseshoes & Hand Grenades", 450540);
INSERT INTO games (title, steam_id) VALUES ("Seed of Evil", 892760);
INSERT INTO games (title, steam_id) VALUES ("The Other Half", 917920);
INSERT INTO games (title, steam_id) VALUES ("War for the Overworld", 230190);
INSERT INTO games (title, steam_id) VALUES ("Medieval Engineers", 333950);
INSERT INTO games (title, steam_id) VALUES ("TechWars: Global Conflict", 523740);
INSERT INTO games (title, steam_id) VALUES ("Tilt Brush", 327140);
INSERT INTO games (title, steam_id) VALUES ("Medieval Engineers - Mod SDK", 349110);
INSERT INTO games (title, steam_id) VALUES ("Nimbatus - The Space Drone Constructor", 383840);
INSERT INTO games (title, steam_id) VALUES ("Medieval Engineers Dedicated Server", 367970);
INSERT INTO games (title, steam_id) VALUES ("Nantucket", 621220);
INSERT INTO games (title, steam_id) VALUES ("Switch", 617570);
INSERT INTO games (title, steam_id) VALUES ("Project Zomboid", 108600);
INSERT INTO games (title, steam_id) VALUES ("Dead Shot Heroes", 820480);
INSERT INTO games (title, steam_id) VALUES ("Dead Shot Heroes Demo", 822730);
INSERT INTO games (title, steam_id) VALUES ("Theatre of Doom", 553020);
INSERT INTO games (title, steam_id) VALUES ("VideoPad", 554820);
INSERT INTO games (title, steam_id) VALUES ("Zup! Arena", 914160);
INSERT INTO games (title, steam_id) VALUES ("Launch Party", 675270);
INSERT INTO games (title, steam_id) VALUES ("Waifu Hunter - Episode 1 : The Runaway Samurai", 946500);
INSERT INTO games (title, steam_id) VALUES ("Strid", 765010);
INSERT INTO games (title, steam_id) VALUES ("Bad North", 688420);
INSERT INTO games (title, steam_id) VALUES ("bLogic Blox", 784110);
INSERT INTO games (title, steam_id) VALUES ("Empires Apart", 530630);
INSERT INTO games (title, steam_id) VALUES ("Project Winter", 774861);
INSERT INTO games (title, steam_id) VALUES ("Lunar Stone: Origin of Blood", 553800);
INSERT INTO games (title, steam_id) VALUES ("Serenade of the Sirens", 901000);
INSERT INTO games (title, steam_id) VALUES ("Blink: Rogues", 739100);
INSERT INTO games (title, steam_id) VALUES ("Godly Corp", 799260);
INSERT INTO games (title, steam_id) VALUES ("Guns of Icarus Online", 209080);
INSERT INTO games (title, steam_id) VALUES ("A Gentlemanly Adventure", 890740);
INSERT INTO games (title, steam_id) VALUES ("Velvet Guard", 822810);
INSERT INTO games (title, steam_id) VALUES ("Space Hulk: Tactics", 492230);
INSERT INTO games (title, steam_id) VALUES ("Entropy 2120", 777730);
INSERT INTO games (title, steam_id) VALUES ("Yu-Gi-Oh! Duel Links", 601510);
INSERT INTO games (title, steam_id) VALUES ("Hide Or Die", 731620);
INSERT INTO games (title, steam_id) VALUES ("Firebase Defence", 941730);
INSERT INTO games (title, steam_id) VALUES ("The Colonists", 677340);
INSERT INTO games (title, steam_id) VALUES ("ShadowSide", 643820);
INSERT INTO games (title, steam_id) VALUES ("HYPERCHARGE: Unboxed", 523660);
INSERT INTO games (title, steam_id) VALUES ("Conan Exiles Dedicated Server", 443030);
INSERT INTO games (title, steam_id) VALUES ("Witch It", 559650);
INSERT INTO games (title, steam_id) VALUES ("Lambda Wars Beta", 270370);
INSERT INTO games (title, steam_id) VALUES ("Lambda Wars Dedicated Server", 319060);
INSERT INTO games (title, steam_id) VALUES ("I wanna be The Cat", 637880);
INSERT INTO games (title, steam_id) VALUES ("Virtual Army: Revolution", 551610);
INSERT INTO games (title, steam_id) VALUES ("Out of the Park Baseball 19", 619290);
INSERT INTO games (title, steam_id) VALUES ("RaceRoom Dedicated Server", 354060);
INSERT INTO games (title, steam_id) VALUES ("PLAYERUNKNOWN'S BATTLEGROUNDS", 578080);
INSERT INTO games (title, steam_id) VALUES ("!Anyway!", 866510);
INSERT INTO games (title, steam_id) VALUES ("TOMORROW DON'T COME", 758570);
INSERT INTO games (title, steam_id) VALUES ("Blackwake", 420290);
INSERT INTO games (title, steam_id) VALUES ("Blackwake Dedicated Server", 423410);
INSERT INTO games (title, steam_id) VALUES ("Valnir Rok", 658980);
INSERT INTO games (title, steam_id) VALUES ("Hero Siege", 269210);
INSERT INTO games (title, steam_id) VALUES ("Capsa", 588120);
INSERT INTO games (title, steam_id) VALUES ("Special Force VR", 673380);
INSERT INTO games (title, steam_id) VALUES ("Zeon 25", 882620);
INSERT INTO games (title, steam_id) VALUES ("UBOAT", 494840);
INSERT INTO games (title, steam_id) VALUES ("Castle Story", 227860);
INSERT INTO games (title, steam_id) VALUES ("Nippon Marathon", 746940);
INSERT INTO games (title, steam_id) VALUES ("Verdun", 242860);
INSERT INTO games (title, steam_id) VALUES ("Labyrinth of Refrain: Coven of Dusk", 566540);
INSERT INTO games (title, steam_id) VALUES ("Bravado", 966370);
INSERT INTO games (title, steam_id) VALUES ("Interstellar Rift", 363360);
INSERT INTO games (title, steam_id) VALUES ("Tannenberg", 633460);
INSERT INTO games (title, steam_id) VALUES ("Furwind", 881750);
INSERT INTO games (title, steam_id) VALUES ("Hectic", 873120);
INSERT INTO games (title, steam_id) VALUES ("VR Trivia Battle", 670830);
INSERT INTO games (title, steam_id) VALUES ("Agony UNRATED", 879420);
INSERT INTO games (title, steam_id) VALUES ("Arena", 717300);
INSERT INTO games (title, steam_id) VALUES ("Nuclear Powered Toaster", 929020);
INSERT INTO games (title, steam_id) VALUES ("Pocket Rogues", 946610);
INSERT INTO games (title, steam_id) VALUES ("Villages", 749820);
INSERT INTO games (title, steam_id) VALUES ("MapleStory 2", 560380);
INSERT INTO games (title, steam_id) VALUES ("心之檻", 951130);
INSERT INTO games (title, steam_id) VALUES ("The Drone Racing League Simulator", 641780);
INSERT INTO games (title, steam_id) VALUES ("Crush Crush", 459820);
INSERT INTO games (title, steam_id) VALUES ("Never Breakup", 904170);
INSERT INTO games (title, steam_id) VALUES ("The Wild Eight", 526160);
INSERT INTO games (title, steam_id) VALUES ("NetHack: Legacy", 837200);
INSERT INTO games (title, steam_id) VALUES ("Slime-san", 473530);
INSERT INTO games (title, steam_id) VALUES ("Star Command Galaxies", 402160);
INSERT INTO games (title, steam_id) VALUES ("Shadow Fear Path to Insanity", 908830);
INSERT INTO games (title, steam_id) VALUES ("The Golf Club™ 2019 Featuring PGA TOUR", 695290);
INSERT INTO games (title, steam_id) VALUES ("Rec Room", 471710);
INSERT INTO games (title, steam_id) VALUES ("Holdfast: Nations At War", 589290);
INSERT INTO games (title, steam_id) VALUES ("Armajet", 895670);
INSERT INTO games (title, steam_id) VALUES ("Din's Legacy", 911550);
INSERT INTO games (title, steam_id) VALUES ("Men of War: Assault Squad 2", 244450);
INSERT INTO games (title, steam_id) VALUES ("Dark Devotion", 718590);
INSERT INTO games (title, steam_id) VALUES ("Noob Squad", 496550);
INSERT INTO games (title, steam_id) VALUES ("Adapt or Perish", 870730);
INSERT INTO games (title, steam_id) VALUES ("Warriors: Rise to Glory!", 582330);
INSERT INTO games (title, steam_id) VALUES ("Meadow", 486310);
INSERT INTO games (title, steam_id) VALUES ("Post Scriptum", 736220);
INSERT INTO games (title, steam_id) VALUES ("Aerofly FS 2 Flight Simulator", 434030);
INSERT INTO games (title, steam_id) VALUES ("Star Conflict", 212070);
INSERT INTO games (title, steam_id) VALUES ("BATTLETECH", 637090);
INSERT INTO games (title, steam_id) VALUES ("They Are Billions", 644930);
INSERT INTO games (title, steam_id) VALUES ("Slappy Ass", 838620);
INSERT INTO games (title, steam_id) VALUES ("Atomic Rancher", 914240);
INSERT INTO games (title, steam_id) VALUES ("Ooblets", 593150);
INSERT INTO games (title, steam_id) VALUES ("Shan Gui 2 山桂贰", 952420);
INSERT INTO games (title, steam_id) VALUES ("Grand Theft Auto V", 271590);
INSERT INTO games (title, steam_id) VALUES ("Hunt For Gods", 576940);
INSERT INTO games (title, steam_id) VALUES ("ZEscape", 517280);
INSERT INTO games (title, steam_id) VALUES ("SteamDolls", 461100);
INSERT INTO games (title, steam_id) VALUES ("Funky Karts", 872690);
INSERT INTO games (title, steam_id) VALUES ("Baba Is You", 736260);
INSERT INTO games (title, steam_id) VALUES ("Stationeers Dedicated Server", 600760);
INSERT INTO games (title, steam_id) VALUES ("BeamNG.drive", 284160);
INSERT INTO games (title, steam_id) VALUES ("Symphonic Mayhem", 954210);
INSERT INTO games (title, steam_id) VALUES ("The Word Is Not The Thing", 730700);
INSERT INTO games (title, steam_id) VALUES ("RealFlight 8", 748460);
INSERT INTO games (title, steam_id) VALUES ("Ultimate Chicken Horse", 386940);
INSERT INTO games (title, steam_id) VALUES ("Lanterns", 806670);
INSERT INTO games (title, steam_id) VALUES ("Two Point Hospital", 535930);
INSERT INTO games (title, steam_id) VALUES ("Good Robot", 358830);
INSERT INTO games (title, steam_id) VALUES ("Stonehearth", 253250);
INSERT INTO games (title, steam_id) VALUES ("Island Maze", 924790);
INSERT INTO games (title, steam_id) VALUES ("11-11 Memories Retold", 735580);
INSERT INTO games (title, steam_id) VALUES ("Star Control: Origins", 271260);
INSERT INTO games (title, steam_id) VALUES ("Armello", 290340);
INSERT INTO games (title, steam_id) VALUES ("Warparty", 777770);
INSERT INTO games (title, steam_id) VALUES ("Wolfenstein II: The New Colossus", 612880);
INSERT INTO games (title, steam_id) VALUES ("Conan Exiles", 440900);
INSERT INTO games (title, steam_id) VALUES ("Kritika Online", 439350);
INSERT INTO games (title, steam_id) VALUES ("Clone Drone in the Danger Zone", 597170);
INSERT INTO games (title, steam_id) VALUES ("Smite - Public Test", 858460);
INSERT INTO games (title, steam_id) VALUES ("Foxhole", 505460);
INSERT INTO games (title, steam_id) VALUES ("Them & Us", 915600);
INSERT INTO games (title, steam_id) VALUES ("Helium Rain", 681330);
INSERT INTO games (title, steam_id) VALUES ("BlazBlue Cross Tag Battle", 702890);
INSERT INTO games (title, steam_id) VALUES ("The Endless Mission", 827880);
INSERT INTO games (title, steam_id) VALUES ("Gran Skrea Online", 595110);
INSERT INTO games (title, steam_id) VALUES ("BallisticNG", 473770);
INSERT INTO games (title, steam_id) VALUES ("Winds of Change", 594130);
INSERT INTO games (title, steam_id) VALUES ("UnderMine", 656350);
INSERT INTO games (title, steam_id) VALUES ("Override", 709440);
INSERT INTO games (title, steam_id) VALUES ("Neverwinter Nights: Enhanced Edition", 704450);
INSERT INTO games (title, steam_id) VALUES ("The Ultimate Clicker Master of the Universe", 924890);
INSERT INTO games (title, steam_id) VALUES ("Cards and Castles", 360730);
INSERT INTO games (title, steam_id) VALUES (".Age", 638510);
INSERT INTO games (title, steam_id) VALUES ("Full Body Workout", 951760);
INSERT INTO games (title, steam_id) VALUES ("Stationeers", 544550);
INSERT INTO games (title, steam_id) VALUES ("Bloody Rally Simulator", 926860);
INSERT INTO games (title, steam_id) VALUES ("Post Scriptum Dedicated Server", 746200);
INSERT INTO games (title, steam_id) VALUES ("Satisfactory", 526870);
INSERT INTO games (title, steam_id) VALUES ("Hunt For Gods Dedicated Server", 609870);
INSERT INTO games (title, steam_id) VALUES ("Duke Dashington Remastered", 894420);
INSERT INTO games (title, steam_id) VALUES ("Professor Chuckenhope", 916620);
INSERT INTO games (title, steam_id) VALUES ("A Mars Journey: Redturtle", 936000);
INSERT INTO games (title, steam_id) VALUES ("Afelhem", 848890);
INSERT INTO games (title, steam_id) VALUES ("When Wardens Fall", 819400);
INSERT INTO games (title, steam_id) VALUES ("樱花片落恋模样 This is a very sweet love story.", 873290);
INSERT INTO games (title, steam_id) VALUES ("河洛群俠傳 (Ho Tu Lo Shu ： The Books of Dragon)", 952860);
INSERT INTO games (title, steam_id) VALUES ("Spellstone", 452230);
INSERT INTO games (title, steam_id) VALUES ("EITR", 350050);
INSERT INTO games (title, steam_id) VALUES ("Zombie Panic! Source Dedicated Server", 17505);
INSERT INTO games (title, steam_id) VALUES ("Onward", 496240);
INSERT INTO games (title, steam_id) VALUES ("Witching Tower", 800200);
INSERT INTO games (title, steam_id) VALUES ("Assetto Corsa Competizione", 805550);
INSERT INTO games (title, steam_id) VALUES ("qb", 601400);
INSERT INTO games (title, steam_id) VALUES ("Orphan", 549700);
INSERT INTO games (title, steam_id) VALUES ("Signal Simulator", 839310);
INSERT INTO games (title, steam_id) VALUES ("Hot Lava", 382560);
INSERT INTO games (title, steam_id) VALUES ("The Montana Chronicles: Montana's Croatoa", 651990);
INSERT INTO games (title, steam_id) VALUES ("Castle Clicker", 704040);
INSERT INTO games (title, steam_id) VALUES ("Need For Seed", 724960);
INSERT INTO games (title, steam_id) VALUES ("Leap of Fate", 363420);
INSERT INTO games (title, steam_id) VALUES ("Her Story", 368370);
INSERT INTO games (title, steam_id) VALUES ("Let the Cat In", 369400);
INSERT INTO games (title, steam_id) VALUES ("Prominence Poker", 384180);
INSERT INTO games (title, steam_id) VALUES ("Euro Truck Simulator 2 - Cabin Accessories", 388470);
INSERT INTO games (title, steam_id) VALUES ("TEKKEN 7", 389730);
INSERT INTO games (title, steam_id) VALUES ("Tactical Craft Online", 415860);
INSERT INTO games (title, steam_id) VALUES ("Woeful Woebots", 450630);
INSERT INTO games (title, steam_id) VALUES ("Quantum Break", 474960);
INSERT INTO games (title, steam_id) VALUES ("Executive Assault 2", 510500);
INSERT INTO games (title, steam_id) VALUES ("Lethal League Blaze", 553310);
INSERT INTO games (title, steam_id) VALUES ("Catmaze", 620220);
INSERT INTO games (title, steam_id) VALUES ("Stars End", 623340);
INSERT INTO games (title, steam_id) VALUES ("Yakuza 0", 638970);
INSERT INTO games (title, steam_id) VALUES ("Flash Point: Fire Rescue", 654220);
INSERT INTO games (title, steam_id) VALUES ("Tracks - The Train Set Game", 657240);
INSERT INTO games (title, steam_id) VALUES ("World War 3", 674020);
INSERT INTO games (title, steam_id) VALUES ("Stick Fight: The Game", 674940);
INSERT INTO games (title, steam_id) VALUES ("Bless Online", 681660);
INSERT INTO games (title, steam_id) VALUES ("The Norwood Suite", 696480);
INSERT INTO games (title, steam_id) VALUES ("CASE 2: Animatronics Survival", 722960);
INSERT INTO games (title, steam_id) VALUES ("Paw Patrol: On A Roll", 758730);
INSERT INTO games (title, steam_id) VALUES ("War Robots", 767560);
INSERT INTO games (title, steam_id) VALUES ("Megadimension Neptunia VIIR", 774511);
INSERT INTO games (title, steam_id) VALUES ("Hyper Universe - Most Popular Starter Pack", 774611);
INSERT INTO games (title, steam_id) VALUES ("Hyper Universe - MVP Starter Pack", 774621);
INSERT INTO games (title, steam_id) VALUES ("Hyper Universe - Hyper All Stars Starter Pack", 774631);
INSERT INTO games (title, steam_id) VALUES ("Hyper Universe - Underdogs Starter Pack", 774641);
INSERT INTO games (title, steam_id) VALUES ("Into the Fray", 893610);
INSERT INTO games (title, steam_id) VALUES ("Speedy Girls - Dream Team", 894900);
INSERT INTO games (title, steam_id) VALUES ("Adventure Portal", 901020);
INSERT INTO games (title, steam_id) VALUES ("Gamers Club", 906490);
INSERT INTO games (title, steam_id) VALUES ("It's a Trap", 912420);
INSERT INTO games (title, steam_id) VALUES ("The Lady Killers", 921140);
INSERT INTO games (title, steam_id) VALUES ("RAM Pressure", 929490);
INSERT INTO games (title, steam_id) VALUES ("General Practitioner", 936960);
INSERT INTO games (title, steam_id) VALUES ("Cats Epic Puzzles", 937290);
INSERT INTO games (title, steam_id) VALUES ("Fap Queen", 942140);
INSERT INTO games (title, steam_id) VALUES ("Ascension: Valley of the Ancients", 942590);
INSERT INTO games (title, steam_id) VALUES ("APB Reloaded", 113400);
INSERT INTO games (title, steam_id) VALUES ("Call of Duty: Black Ops II", 202970);
INSERT INTO games (title, steam_id) VALUES ("Call of Duty: Black Ops II - Multiplayer", 202990);
INSERT INTO games (title, steam_id) VALUES ("Castle Crashers", 204360);
INSERT INTO games (title, steam_id) VALUES ("Batman™: Arkham Knight", 208650);
INSERT INTO games (title, steam_id) VALUES ("Call of Duty: Black Ops II - Zombies", 212910);
INSERT INTO games (title, steam_id) VALUES ("TowerFall Ascension", 251470);
INSERT INTO games (title, steam_id) VALUES ("XCOM 2", 268500);
INSERT INTO games (title, steam_id) VALUES ("Redirection", 305760);
INSERT INTO games (title, steam_id) VALUES ("The Elder Scrolls Online", 306130);
INSERT INTO games (title, steam_id) VALUES ("Dead or Alive 5 Last Round", 311730);
INSERT INTO games (title, steam_id) VALUES ("Strange Brigade", 312670);
INSERT INTO games (title, steam_id) VALUES ("Life is Strange™", 319630);
INSERT INTO games (title, steam_id) VALUES ("HuniePop", 339800);
INSERT INTO games (title, steam_id) VALUES ("Armed with Wings: Rearmed", 340580);
INSERT INTO games (title, steam_id) VALUES ("Software Inc.", 362620);
INSERT INTO games (title, steam_id) VALUES ("An Elephant's Journey", 942670);
INSERT INTO games (title, steam_id) VALUES ("Escape the Enterprise", 944370);
INSERT INTO games (title, steam_id) VALUES ("Hentai Neighbors", 946090);
INSERT INTO games (title, steam_id) VALUES ("Russian roulette", 949630);
INSERT INTO games (title, steam_id) VALUES ("Volcan Defend the Tower", 950510);
INSERT INTO games (title, steam_id) VALUES ("Dominatrix Simulator: Threshold", 953270);
INSERT INTO games (title, steam_id) VALUES ("HOT GIRLS VR", 953610);
INSERT INTO games (title, steam_id) VALUES ("Onii-chan Asobo", 954610);
INSERT INTO games (title, steam_id) VALUES ("Cute Girls", 958300);
INSERT INTO games (title, steam_id) VALUES ("the earth is a better person than me", 959710);
INSERT INTO games (title, steam_id) VALUES ("Grand Designer Features pack", 964480);
INSERT INTO games (title, steam_id) VALUES ("Kara no Shojo", 965810);
INSERT INTO games (title, steam_id) VALUES ("Super Meat Boy Race Mode", 969710);
INSERT INTO games (title, steam_id) VALUES ("Counter-Strike", 10);
INSERT INTO games (title, steam_id) VALUES ("F.E.A.R. 2: Project Origin", 16450);
INSERT INTO games (title, steam_id) VALUES ("CHANGE: A Homeless Survival Experience", 926140);
INSERT INTO games (title, steam_id) VALUES ("Death's Gambit", 356650);
INSERT INTO games (title, steam_id) VALUES ("EXAPUNKS", 716490);
INSERT INTO games (title, steam_id) VALUES ("PRATAGON", 950780);
INSERT INTO games (title, steam_id) VALUES ("War of Conquest", 767300);
INSERT INTO games (title, steam_id) VALUES ("DEEP SPACE WAIFU", 639790);
INSERT INTO games (title, steam_id) VALUES ("LEGO® The Incredibles", 818320);
INSERT INTO games (title, steam_id) VALUES ("Allergenium", 871860);
INSERT INTO games (title, steam_id) VALUES ("Darwin Project", 544920);
INSERT INTO games (title, steam_id) VALUES ("Eternal Card Game", 531640);
INSERT INTO games (title, steam_id) VALUES ("Monster League", 767360);
INSERT INTO games (title, steam_id) VALUES ("SpedV", 839200);
INSERT INTO games (title, steam_id) VALUES ("Pixel World", 963190);
INSERT INTO games (title, steam_id) VALUES ("Midair", 439370);
INSERT INTO games (title, steam_id) VALUES ("Differently Fast", 697430);
INSERT INTO games (title, steam_id) VALUES ("Pitiri 1977", 305740);
INSERT INTO games (title, steam_id) VALUES ("In Darkness", 781680);
INSERT INTO games (title, steam_id) VALUES ("Blackjack of Strip", 945700);
INSERT INTO games (title, steam_id) VALUES ("Space Gladiator", 965110);
INSERT INTO games (title, steam_id) VALUES ("Aqua Lungers", 820640);
INSERT INTO games (title, steam_id) VALUES ("NAMELESS", 834440);
INSERT INTO games (title, steam_id) VALUES ("Fear The Wolves", 819500);
INSERT INTO games (title, steam_id) VALUES ("Natural Selection 2 Dedicated Server", 4940);
INSERT INTO games (title, steam_id) VALUES ("Natural Selection 2", 4920);
INSERT INTO games (title, steam_id) VALUES ("Estranged: Act II", 582890);
INSERT INTO games (title, steam_id) VALUES ("Beer'em Up", 945880);
INSERT INTO games (title, steam_id) VALUES ("Jurassic World Evolution", 648350);
INSERT INTO games (title, steam_id) VALUES ("Etherian", 836460);
INSERT INTO games (title, steam_id) VALUES ("868-HACK", 274700);
INSERT INTO games (title, steam_id) VALUES ("Type Defense", 904440);
INSERT INTO games (title, steam_id) VALUES ("Project 1v1 Closed Technical Test", 540390);
INSERT INTO games (title, steam_id) VALUES ("WWE 2K19", 817130);
INSERT INTO games (title, steam_id) VALUES ("Brainstorm", 870940);
INSERT INTO games (title, steam_id) VALUES ("Stellar Tactics", 465490);
INSERT INTO games (title, steam_id) VALUES ("Project Hospital", 868360);
INSERT INTO games (title, steam_id) VALUES ("Double Cross", 838010);
INSERT INTO games (title, steam_id) VALUES ("BELOW", 250680);
INSERT INTO games (title, steam_id) VALUES ("Hotel Transylvania Popstic", 884370);
INSERT INTO games (title, steam_id) VALUES ("Fallout Shelter", 588430);
INSERT INTO games (title, steam_id) VALUES ("Princess.Loot.Pixel.Again", 414290);
INSERT INTO games (title, steam_id) VALUES ("Dungetris", 462200);
INSERT INTO games (title, steam_id) VALUES ("The Bard's Tale IV", 566090);
INSERT INTO games (title, steam_id) VALUES ("LOTUS-Simulator Map-Editor", 870500);
INSERT INTO games (title, steam_id) VALUES ("LOTUS-Simulator", 370350);
INSERT INTO games (title, steam_id) VALUES ("Princess.Loot.Pixel.Again x2", 718090);
INSERT INTO games (title, steam_id) VALUES ("From The Depths", 268650);
INSERT INTO games (title, steam_id) VALUES ("Corrupted Commander", 953220);
INSERT INTO games (title, steam_id) VALUES ("LOTUS-Simulator Content-Tool", 870490);
INSERT INTO games (title, steam_id) VALUES ("Tom Clancy's Rainbow Six Siege", 359550);
INSERT INTO games (title, steam_id) VALUES ("Murder Miners", 274900);
INSERT INTO games (title, steam_id) VALUES ("Pirates of the Polygon Sea", 479020);
INSERT INTO games (title, steam_id) VALUES ("Fruit Tower Defense", 911760);
INSERT INTO games (title, steam_id) VALUES ("Mowin' & Throwin'", 762030);
INSERT INTO games (title, steam_id) VALUES ("Dreadnought", 835860);
INSERT INTO games (title, steam_id) VALUES ("Oxygen Not Included", 457140);
INSERT INTO games (title, steam_id) VALUES ("The Banner Saga", 237990);
INSERT INTO games (title, steam_id) VALUES ("Through the Ages", 758370);
INSERT INTO games (title, steam_id) VALUES ("COLINA: Legacy", 371650);
INSERT INTO games (title, steam_id) VALUES ("QuiVr", 489380);
INSERT INTO games (title, steam_id) VALUES ("Miscreated: Experimental Server", 912290);
INSERT INTO games (title, steam_id) VALUES ("StickyBots", 889400);
INSERT INTO games (title, steam_id) VALUES ("Res Judicata: Vale of Myth - Strategy Guide", 731610);
INSERT INTO games (title, steam_id) VALUES ("The Maestros", 553560);
INSERT INTO games (title, steam_id) VALUES ("Overcooked! 2", 728880);
INSERT INTO games (title, steam_id) VALUES ("Cossacks II: Battle for Europe", 4890);
INSERT INTO games (title, steam_id) VALUES ("Ballistic Overkill Dedicated Server", 416880);
INSERT INTO games (title, steam_id) VALUES ("SHELL", 964810);
INSERT INTO games (title, steam_id) VALUES ("VRChat", 438100);
INSERT INTO games (title, steam_id) VALUES ("Raw Data", 436320);
INSERT INTO games (title, steam_id) VALUES ("Creativerse", 280790);
INSERT INTO games (title, steam_id) VALUES ("Blood Harvest 3", 851180);
INSERT INTO games (title, steam_id) VALUES ("Lost Wing", 556960);
INSERT INTO games (title, steam_id) VALUES ("Fractured Lands", 751240);
INSERT INTO games (title, steam_id) VALUES ("Don't Starve", 219740);
INSERT INTO games (title, steam_id) VALUES ("Debris", 669660);
INSERT INTO games (title, steam_id) VALUES ("SimpleRockets 2", 870200);
INSERT INTO games (title, steam_id) VALUES ("One More Roll", 911520);
INSERT INTO games (title, steam_id) VALUES ("Serious Sam 2017 Editor", 564380);
INSERT INTO games (title, steam_id) VALUES ("Serious Sam 2017 Dedicated Server", 564390);
INSERT INTO games (title, steam_id) VALUES ("Serious Sam Fusion 2017 (beta)", 564310);
INSERT INTO games (title, steam_id) VALUES ("SMITE", 386360);
INSERT INTO games (title, steam_id) VALUES ("Serious Sam 3 VR: BFE", 567670);
INSERT INTO games (title, steam_id) VALUES ("Serious Sam VR: The Second Encounter", 552460);
INSERT INTO games (title, steam_id) VALUES ("Staxel", 405710);
INSERT INTO games (title, steam_id) VALUES ("Not my day", 951320);
INSERT INTO games (title, steam_id) VALUES ("Shrines Of Sacred Essenсe", 949830);
INSERT INTO games (title, steam_id) VALUES ("Serious Sam VR: The First Encounter", 552450);
INSERT INTO games (title, steam_id) VALUES ("Zombie Panic! Source", 17500);
INSERT INTO games (title, steam_id) VALUES ("ToeJam & Earl: Back in the Groove", 516110);
INSERT INTO games (title, steam_id) VALUES ("Elemental War", 917850);
INSERT INTO games (title, steam_id) VALUES ("Holodrive", 370770);
INSERT INTO games (title, steam_id) VALUES ("Remnants", 574180);
INSERT INTO games (title, steam_id) VALUES ("MatchyGotchy", 772700);
INSERT INTO games (title, steam_id) VALUES ("Quible Sphere", 840380);
INSERT INTO games (title, steam_id) VALUES ("Coffence", 583240);
INSERT INTO games (title, steam_id) VALUES ("AdVenture Capitalist", 346900);
INSERT INTO games (title, steam_id) VALUES ("Rend", 547860);
INSERT INTO games (title, steam_id) VALUES ("Qybe", 868500);
INSERT INTO games (title, steam_id) VALUES ("Age of Gladiators II: Rome", 783590);
INSERT INTO games (title, steam_id) VALUES ("Shadowcrawl", 757730);
INSERT INTO games (title, steam_id) VALUES ("Rend Server", 550790);
INSERT INTO games (title, steam_id) VALUES ("My Summer Car", 516750);
INSERT INTO games (title, steam_id) VALUES ("Atom Universe", 394120);
INSERT INTO games (title, steam_id) VALUES ("The Horologist's Legacy", 957890);
INSERT INTO games (title, steam_id) VALUES ("Invisigun Heroes", 375750);
INSERT INTO games (title, steam_id) VALUES ("Empires of the Undergrowth", 463530);
INSERT INTO games (title, steam_id) VALUES ("Rocket League", 252950);
INSERT INTO games (title, steam_id) VALUES ("AccuRC 2", 495290);
INSERT INTO games (title, steam_id) VALUES ("Skeletal Dance Party", 599160);
INSERT INTO games (title, steam_id) VALUES ("Genetic Disaster", 672460);
INSERT INTO games (title, steam_id) VALUES ("Escape Doodland", 670930);
INSERT INTO games (title, steam_id) VALUES ("Killer Queen Black", 663670);
INSERT INTO games (title, steam_id) VALUES ("SCP: Secret Laboratory", 700330);
INSERT INTO games (title, steam_id) VALUES ("Sub Rosa", 272230);
INSERT INTO games (title, steam_id) VALUES ("Soundboxing", 517130);
INSERT INTO games (title, steam_id) VALUES ("Heroes of Delum", 676700);
INSERT INTO games (title, steam_id) VALUES ("Guns and Ghosts", 945110);
INSERT INTO games (title, steam_id) VALUES ("rumii", 872440);
INSERT INTO games (title, steam_id) VALUES ("Pathfinder: Kingmaker", 640820);
INSERT INTO games (title, steam_id) VALUES ("Axe Throw VR", 928370);
INSERT INTO games (title, steam_id) VALUES ("Audiate", 886480);
INSERT INTO games (title, steam_id) VALUES ("The Unlikely Legend of Rusty Pup", 800690);
INSERT INTO games (title, steam_id) VALUES ("Armored Battle Crew", 814740);
INSERT INTO games (title, steam_id) VALUES ("Cinderella Escape 2 Revenge", 710030);
INSERT INTO games (title, steam_id) VALUES ("High Fidelity", 390540);
INSERT INTO games (title, steam_id) VALUES ("RWBY: Grimm Eclipse", 418340);
INSERT INTO games (title, steam_id) VALUES ("Bonds Demo", 964000);
INSERT INTO games (title, steam_id) VALUES ("No Body Home", 794420);
INSERT INTO games (title, steam_id) VALUES ("SteamVR", 250820);
INSERT INTO games (title, steam_id) VALUES ("Headliner: NoviNews", 918820);
INSERT INTO games (title, steam_id) VALUES ("EONIA", 826180);
INSERT INTO games (title, steam_id) VALUES ("Candice DeBébé's Scandalous Secrets", 941540);
INSERT INTO games (title, steam_id) VALUES ("ARK: Survival Evolved", 346110);
INSERT INTO games (title, steam_id) VALUES ("Rust - Staging Branch", 700580);
INSERT INTO games (title, steam_id) VALUES ("The Blackout Club", 599080);
INSERT INTO games (title, steam_id) VALUES ("Epic Skater 2", 879740);
INSERT INTO games (title, steam_id) VALUES ("Rust Dedicated Server", 258550);
INSERT INTO games (title, steam_id) VALUES ("Squad", 393380);
INSERT INTO games (title, steam_id) VALUES ("Nightwolf: Survive the Megadome", 760050);
INSERT INTO games (title, steam_id) VALUES ("Lamplight Station", 753490);
INSERT INTO games (title, steam_id) VALUES ("Head", 966810);
INSERT INTO games (title, steam_id) VALUES ("Be My Cat", 966830);
INSERT INTO games (title, steam_id) VALUES ("Draid Demo", 863360);
INSERT INTO games (title, steam_id) VALUES ("Star Trek Timelines", 600750);
INSERT INTO games (title, steam_id) VALUES ("Corpse Party: Book of Shadows", 778390);
INSERT INTO games (title, steam_id) VALUES ("Squad Dedicated Server", 403240);
INSERT INTO games (title, steam_id) VALUES ("Res Judicata: Vale of Myth - OST", 882550);
INSERT INTO games (title, steam_id) VALUES ("Timespinner", 368620);
INSERT INTO games (title, steam_id) VALUES ("Gender Bender", 967020);
INSERT INTO games (title, steam_id) VALUES ("PAYDAY 2", 218620);
INSERT INTO games (title, steam_id) VALUES ("BattleBeasts", 830580);
INSERT INTO games (title, steam_id) VALUES ("Flat Kingdom Paper's Cut Edition", 405970);
INSERT INTO games (title, steam_id) VALUES ("AegisM", 845040);
INSERT INTO games (title, steam_id) VALUES ("Diner Bros", 846800);
INSERT INTO games (title, steam_id) VALUES ("Dungeon Defenders II", 236110);
INSERT INTO games (title, steam_id) VALUES ("Beer Pong League", 642190);
INSERT INTO games (title, steam_id) VALUES ("Arcfall", 623310);
INSERT INTO games (title, steam_id) VALUES ("The Long Dark", 305620);
INSERT INTO games (title, steam_id) VALUES ("The Land of the Seazogs", 839210);
INSERT INTO games (title, steam_id) VALUES ("ADAPTR", 516570);
INSERT INTO games (title, steam_id) VALUES ("Odd Island", 739810);
INSERT INTO games (title, steam_id) VALUES ("A Killer's Sorrow", 937070);
INSERT INTO games (title, steam_id) VALUES ("Vreal", 440120);
INSERT INTO games (title, steam_id) VALUES ("Sector Six", 465020);
INSERT INTO games (title, steam_id) VALUES ("The Isle", 376210);
INSERT INTO games (title, steam_id) VALUES ("Rocksmith® 2014 Edition - Remastered", 221680);
INSERT INTO games (title, steam_id) VALUES ("The Quiet Man", 790540);
INSERT INTO games (title, steam_id) VALUES ("Maia", 252250);
INSERT INTO games (title, steam_id) VALUES ("Dark Places", 926810);
INSERT INTO games (title, steam_id) VALUES ("GRAL", 718020);
INSERT INTO games (title, steam_id) VALUES ("Scraper: First Strike", 909780);
INSERT INTO games (title, steam_id) VALUES ("Street Fighter V", 310950);
INSERT INTO games (title, steam_id) VALUES ("VOLTED", 605920);
